### ISSUE TITLE
  13:12  error  Parsing error: Unexpected trailing comma after rest property?

### ISSUE THREAD

**Issue by scheung38** [neekey/demo-react-master-detail-view#2]
/app/components/layout/cont.MasterDetail.js
  13:12  error  Parsing error: Unexpected trailing comma after rest property

✖ 1 problem (1 error, 0 warnings)

**Comment by neekey** [comment]
@scheung38 thanks for reporting, will take a look later today!

**Comment by scheung38** [comment]
Webstorm setting is Preference - Tools and File Watch Babel.

Also ES6 standard setting correct?

**Comment by scheung38** [comment]
Just doesnt like the ...rest statement

**Comment by neekey** [comment]
Fixed https://github.com/neekey/demo-react-master-detail-view/commit/b191c101773ff1acdf05bbacc74bf7e66ed94427, you don't have to use webstorm babel watcher, it's just a syntax warning threw up by eslint.
